# Re:VIEW version number supported by this settings file.
review_version: 5.0

inherit: ["../config-base.yml"]
bookname: Legendary Moonlight Sculptor Vol 5
booktitle: The Legendary Moonlight Sculptor, Vol. 05
isbn: "9788958579076"
date: 2007-05-26