# Re:VIEW version number supported by this settings file.
review_version: 5.0

inherit: ["../config-base.yml"]
bookname: Legendary Moonlight Sculptor Vol 6
booktitle: The Legendary Moonlight Sculptor, Vol. 06
isbn: "9788925701271"
date: 2007-06-29